// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

#pragma warning disable CS8669 // We may leak nullable annotations into generated code.

namespace Formatters.DR.Dto
{
	using MsgPack = global::MessagePack;

	internal sealed class DemoPingResponseDtoFormatter : MsgPack::Formatters.IMessagePackFormatter<global::DR.Dto.DemoPingResponseDto>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::DR.Dto.DemoPingResponseDto value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			MsgPack::IFormatterResolver formatterResolver = options.Resolver;
			writer.WriteArrayHeader(3);
			writer.Write(value.Success);
			MsgPack::FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Reply, options);
			writer.Write(value.ServerTicksUtc);
		}

		public global::DR.Dto.DemoPingResponseDto Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			options.Security.DepthStep(ref reader);
			MsgPack::IFormatterResolver formatterResolver = options.Resolver;
			var length = reader.ReadArrayHeader();
			var ____result = new global::DR.Dto.DemoPingResponseDto();

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						____result.Success = reader.ReadBoolean();
						break;
					case 1:
						____result.Reply = MsgPack::FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
						break;
					case 2:
						____result.ServerTicksUtc = reader.ReadInt64();
						break;
					default:
						reader.Skip();
						break;
				}
			}

			reader.Depth--;
			return ____result;
		}
	}
}
